### PR TITLE
Refactor/backend-ts

### PR DESCRIPTION
**Pull request by darrenkuro**
Refactored the backend to TypeScript, added support for drizzle-orm for database, changed a little of the build process and Dockerfile also; various stuff but mainly just focused on the architectural design and general structure of the backend... Again, any review/feedback/suggestion welcome. **Maybe do not merge yet though**, since It's not exactly finished functionally for some classes and functions, but the good thing is that they are all self-contained and everything builds ok and no end point is being called except for that one single end-point so... 

PR is more just to see if there's anything I should be changing drastically before I head too far down this road. 

Also: forgot to turn off auto formatting so accidentally changed two frontend files. Does anyone oppose prettier? (Also @cubernetes I lied the other day, they do not mix spaces and tabs; guess it was about another formatter I've read.) 

Didn't really change any API endpoints logic, only refactored it to ts and structurally modified some small parts. Hopefully everything is pretty clear and self-explanatory so far. 

I do have some thoughts about how the /friends endpoints are designed though (also how the schema of friends table actually) so that is still a working process; too tired to think clearly, will try to finish that later tonight. Will be attempting to learn tap next and write some tests.

### CODE REVIEW

**Review by cubernetes — APPROVED** [review]
Skimmed everything, lots of TS and fastify which I'm not familiar with, so yeah can't tell if there's code smell or bad practices. The only thing that stood out to me from the outside is the duplication of the schema.sql in schema.ts, but yeah no idea how to solve that issue. Maybe write a sql to drizzleORM transpiler LOL

I approve, but as you said yourself, merge whenever you want.

**Comment by bejasch** [comment]
This commit doesn't build for me:
1. problematic line: `> tsc --noEmit && node build.js` in backend/package.json
```
3.366 node:internal/modules/cjs/loader:1143
3.366   throw err;
3.366   ^
3.366
3.366 Error: Cannot find module '/app/build.js'
```
2. # npm audit report: (won't be the problem)
```
esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
```

**Comment by darrenkuro** [comment]
> This commit doesn't build for me:
> 
> 1. problematic line: `> tsc --noEmit && node build.js` in backend/package.json
> 
> ```
> 3.366 node:internal/modules/cjs/loader:1143
> 3.366   throw err;
> 3.366   ^
> 3.366
> 3.366 Error: Cannot find module '/app/build.js'
> ```
> 
>  2. npm audit report: (won't be the problem)
> 
> ```
> esbuild  <=0.24.2
> Severity: moderate
> esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
> ```

That is correct since I am currently pushing and making changes on this branch. The importance of the PR is more on the design side anyway (structure and model, etc.) since functionally or visually nothing's changed. Will be finishing changes before merge though.

**Comment by darrenkuro** [comment]
@bejasch This current commit should build I believe.
